#define PJMEDIA_HAS_WEBRTC_AEC 1
#define PJMEDIA_HAS_AMR 1
#define PJMEDIA_HAS_AMR_WB 1
#define PJMEDIA_CODEC_L16_HAS_8KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_8KHZ_STEREO 1
#define PJMEDIA_CODEC_L16_HAS_16KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_16KHZ_STEREO 1
#define PJMEDIA_CODEC_L16_HAS_48KHZ_MONO 1
#define PJMEDIA_CODEC_L16_HAS_48KHZ_STEREO 1
#define PJMEDIA_HAS_G7221_CODEC 1
#define PJMEDIA_HAS_G722_CODEC 1
#define PJ_EXCLUDE_BENCHMARK_TESTS 1
// #define PJ_HAS_SSL_SOCK 1
#define PJSIP_HAS_DIGEST_AKA_AUTH   1
// #define PJMEDIA_AUDIO_DEV_HAS_ALSA 1
